### ISSUE TITLE
Parsing Rmarkdown-Files to Anki-Flashcards

### ISSUE THREAD

**Issue by henningsway** [liammclennan/SpacedRepetition#1]
Dear Liam,

I just found out about your program and haven't gotten around to test it so far.
I am looking for an elegant solution to parse multiple *.Rmd-Files and extract Questions and Answers and produce nicely formated Anki Flashcards with this input.

Ideally it would be possible to include nicely formated `R input` and possibly even `output` into the cards, though this will be difficult via csv, i guess.

Does your program accept the *.Rmd-Files directly or do they have to be converted to *.md first? How flexible ist the markup for the Question- and Answer-parts?

If there is any other project-documentation, that I've missed, please point me in the right direction. :)

Kind regards,
Henning

**Comment by liammclennan** [comment]
Hi Henning,
Unfortunately this program doesn't have any particular support for R markdown, and is not very sophisticated. It simply parses a basic text format for questions and answers. 
Regards,
Liam.
